name: Build LaTeX document

on: 
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches:
      - master


jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document Introduction
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/Introduction/
          
      - name: Compile LaTeX document Linear_Algebra_Four_Fundamental_Subspaces
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/Linear_Algebra_Four_Fundamental_Subspaces/
          
      - name: Compile LaTeX document Linear_Algebra_Four_Fundamental_Subspaces_part2
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/Linear_Algebra_Four_Fundamental_Subspaces_part2/
          
      - name: Compile LaTeX document Linear_Algebra_Four_Fundamental_Subspaces_use_case
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/Linear_Algebra_Four_Fundamental_Subspaces_use_case/
          
      - name: Compile LaTeX document Least_Squares_and_Quadratic_Programming
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/Least_Squares_and_Quadratic_Programming/
          
      - name: Compile LaTeX document Domain_Convex_Domains
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/Domain_Convex_Domains/
          
      - name: Compile LaTeX document Linear_inequality_representation_of_convex_domains
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/Linear_inequality_representation_of_convex_domains/
          
            


      - name: Save Introduction artifact
        uses: actions/upload-artifact@v1
        with:
          name: Introduction.pdf
          path: Slides/Introduction/main.pdf

      - name: Save Linear_Algebra_Four_Fundamental_Subspaces artifact
        uses: actions/upload-artifact@v1
        with:
          name: Linear_Algebra_Four_Fundamental_Subspaces.pdf
          path: Slides/Linear_Algebra_Four_Fundamental_Subspaces/main.pdf

      - name: Save Linear_Algebra_Four_Fundamental_Subspaces_part2 artifact
        uses: actions/upload-artifact@v1
        with:
          name: Linear_Algebra_Four_Fundamental_Subspaces_part2.pdf
          path: Slides/Linear_Algebra_Four_Fundamental_Subspaces_part2/main.pdf

      - name: Save Linear_Algebra_Four_Fundamental_Subspaces_use_case artifact
        uses: actions/upload-artifact@v1
        with:
          name: Linear_Algebra_Four_Fundamental_Subspaces_use_case.pdf
          path: Slides/Linear_Algebra_Four_Fundamental_Subspaces_use_case/main.pdf

      - name: Save Least_Squares_and_Quadratic_Programming artifact
        uses: actions/upload-artifact@v1
        with:
          name: Least_Squares_and_Quadratic_Programming.pdf
          path: Slides/Least_Squares_and_Quadratic_Programming/main.pdf

      - name: Save Domain_Convex_Domains artifact
        uses: actions/upload-artifact@v1
        with:
          name: Domain_Convex_Domains.pdf
          path: Slides/Domain_Convex_Domains/main.pdf

      - name: Save Linear_inequality_representation_of_convex_domains artifact
        uses: actions/upload-artifact@v1
        with:
          name: Linear_inequality_representation_of_convex_domains.pdf
          path: Slides/Linear_inequality_representation_of_convex_domains/main.pdf

          
      - name: Update compiled PDFs in git repository
        if: github.event.pull_request.merged == true || (github.event_name == 'push' && github.ref == 'refs/heads/master')
        run: |
          git config --global user.name 'CI PDF compiler'
          git config --global user.email '<>'
          git add Slides/Introduction/main.pdf
          git add Slides/Linear_Algebra_Four_Fundamental_Subspaces/main.pdf
          git add Slides/Linear_Algebra_Four_Fundamental_Subspaces_part2/main.pdf
          git add Slides/Linear_Algebra_Four_Fundamental_Subspaces_use_case/main.pdf
          git add Slides/Least_Squares_and_Quadratic_Programming/main.pdf
          git add Slides/Domain_Convex_Domains/main.pdf
          git add Slides/Linear_inequality_representation_of_convex_domains/main.pdf
          
          git commit -m "Update compiled PDFs"
          git push
